name: prebuild
on:
  push:
jobs:
  prebuild:
    name: "Prebuild binaries"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 14
          - 16

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          version: 3

      - name: Install C++ compiler
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install visualstudio2019-workload-vctools -y

      - name: Install dependencies
        run: npm install

      - name: Pre-build
        run: npx prebuildify --strip -t 14.16.0
