name: build
on:
  push:
jobs:
  build:
    name: "Prebuild binaries"
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 14
          - 16

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          version: 3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: "Sets to use msbuild"
        run: npm config set msvs_version 2022

      - name: Install dependencies
        run: npm install

      - name: Pre-build
        run: npx prebuildify --strip --all
